/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Defaults */
        get: operations["get_defaults_api_v1_me_defaults_get"];
        /** Update Defaults */
        put: operations["update_defaults_api_v1_me_defaults_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_v1_me_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/days/{day_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Day */
        put: operations["save_day_api_v1_me_days__day_date__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/meal-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meal Types */
        get: operations["list_meal_types_api_v1_catalog_meal_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requests For Day */
        get: operations["requests_for_day_api_v1_admin_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/requests/{user_id}/{day_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save For User */
        put: operations["save_for_user_api_v1_admin_requests__user_id___day_date__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Defaults */
        get: operations["get_user_defaults_api_v1_admin_users__user_id__defaults_get"];
        /** Update User Defaults */
        put: operations["update_user_defaults_api_v1_admin_users__user_id__defaults_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Calendar */
        get: operations["get_user_calendar_api_v1_admin_users__user_id__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accountant/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Report */
        get: operations["daily_report_api_v1_accountant_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accountant/report/period": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period Report */
        get: operations["period_report_api_v1_accountant_report_period_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accountant/report/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily Report Export */
        get: operations["daily_report_export_api_v1_accountant_report_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accountant/report/period/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period Report Export */
        get: operations["period_report_export_api_v1_accountant_report_period_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/halls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Halls */
        get: operations["list_halls_api_v1_operator_halls_get"];
        put?: never;
        /** Create Hall */
        post: operations["create_hall_api_v1_operator_halls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/halls/{hall_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Hall */
        put: operations["update_hall_api_v1_operator_halls__hall_id__put"];
        post?: never;
        /** Delete Hall */
        delete: operations["delete_hall_api_v1_operator_halls__hall_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/meal-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meal Types */
        get: operations["list_meal_types_api_v1_operator_meal_types_get"];
        put?: never;
        /** Create Meal Type */
        post: operations["create_meal_type_api_v1_operator_meal_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/meal-types/{meal_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Meal Type */
        put: operations["update_meal_type_api_v1_operator_meal_types__meal_type_id__put"];
        post?: never;
        /** Delete Meal Type */
        delete: operations["delete_meal_type_api_v1_operator_meal_types__meal_type_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_operator_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_operator_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update User */
        put: operations["update_user_api_v1_operator_users__user_id__put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_operator_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Password */
        put: operations["set_password_api_v1_operator_users__user_id__password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/users/{user_id}/halls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Halls */
        put: operations["set_halls_api_v1_operator_users__user_id__halls_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_operator_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_v1_operator_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/schedule-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_operator_schedule_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_operator_schedule_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/schedule-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Rule */
        put: operations["update_rule_api_v1_operator_schedule_rules__rule_id__put"];
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_operator_schedule_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/days/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_v1_operator_days_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operator/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Logs */
        get: operations["list_logs_api_v1_operator_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminDayOut */
        AdminDayOut: {
            user: components["schemas"]["UserOut"];
            day: components["schemas"]["DayStateOut"];
        };
        /** AdminUserOut */
        AdminUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Default Meal Type Id */
            default_meal_type_id: string | null;
            /**
             * Hall Ids
             * @default []
             */
            hall_ids: string[];
        };
        /** AuditLogOut */
        AuditLogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DailyReportOut */
        DailyReportOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Halls */
            halls: components["schemas"]["HallReportOut"][];
            /** Grand Total */
            grand_total: number;
            /** Grand Reserve Total */
            grand_reserve_total: number;
        };
        /** DayStateOut */
        DayStateOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Meal Type Id */
            meal_type_id: string | null;
            /** Items */
            items: components["schemas"]["MealStateOut"][];
            /** Version */
            version: number | null;
            /** Has Request */
            has_request: boolean;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /** Available */
            available: boolean;
            /** Editable */
            editable: boolean;
        };
        /** DayUpdateRequest */
        DayUpdateRequest: {
            /** Meal Type Id */
            meal_type_id?: string | null;
            /**
             * Meals
             * @default {}
             */
            meals: {
                [key: string]: boolean;
            };
            /** Version */
            version?: number | null;
        };
        /** DefaultsOut */
        DefaultsOut: {
            /** Default Meal Type Id */
            default_meal_type_id: string | null;
            /** Meals */
            meals: {
                [key: string]: boolean;
            };
        };
        /** DefaultsUpdate */
        DefaultsUpdate: {
            /** Default Meal Type Id */
            default_meal_type_id?: string | null;
            /** Meals */
            meals: {
                [key: string]: boolean;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HallBrief */
        HallBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** HallIn */
        HallIn: {
            /** Name */
            name: string;
        };
        /** HallOut */
        HallOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** HallPeriodReportOut */
        HallPeriodReportOut: {
            /**
             * Hall Id
             * Format: uuid
             */
            hall_id: string;
            /** Hall Name */
            hall_name: string;
            /** Meals */
            meals: components["schemas"]["MealReportOut"][];
            /** Period Total */
            period_total: number;
            /** Period Reserve Total */
            period_reserve_total: number;
        };
        /** HallReportOut */
        HallReportOut: {
            /**
             * Hall Id
             * Format: uuid
             */
            hall_id: string;
            /** Hall Name */
            hall_name: string;
            /** Meals */
            meals: components["schemas"]["MealReportOut"][];
            /** Day Total */
            day_total: number;
            /** Day Reserve Total */
            day_reserve_total: number;
        };
        /** HallUpdate */
        HallUpdate: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** HallsSet */
        HallsSet: {
            /** Hall Ids */
            hall_ids: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Default Meal Type Id */
            default_meal_type_id: string | null;
            /**
             * Halls
             * @default []
             */
            halls: components["schemas"]["HallBrief"][];
        };
        /**
         * MealKind
         * @enum {string}
         */
        MealKind: "breakfast" | "lunch" | "snack" | "dinner";
        /** MealReportOut */
        MealReportOut: {
            meal_kind: components["schemas"]["MealKind"];
            /** By Type */
            by_type: components["schemas"]["TypeCountOut"][];
            /** Reserve By Type */
            reserve_by_type: components["schemas"]["TypeCountOut"][];
            /** Total */
            total: number;
            /** Reserve Total */
            reserve_total: number;
        };
        /** MealStateOut */
        MealStateOut: {
            meal_kind: components["schemas"]["MealKind"];
            /** Is Served */
            is_served: boolean;
            /** Is Going */
            is_going: boolean;
            /** Is Reserve */
            is_reserve: boolean;
        };
        /** MealTypeIn */
        MealTypeIn: {
            /** Name */
            name: string;
            /** Icon */
            icon?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** MealTypeOut */
        MealTypeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Icon */
            icon: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /** MealTypeUpdate */
        MealTypeUpdate: {
            /** Name */
            name?: string | null;
            /** Icon */
            icon?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** OperatorUserCreate */
        OperatorUserCreate: {
            /** Login */
            login: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Hall Ids
             * @default []
             */
            hall_ids: string[];
            /** Default Meal Type Id */
            default_meal_type_id?: string | null;
        };
        /** OperatorUserOut */
        OperatorUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Default Meal Type Id */
            default_meal_type_id: string | null;
            /**
             * Hall Ids
             * @default []
             */
            hall_ids: string[];
        };
        /** OperatorUserUpdate */
        OperatorUserUpdate: {
            /** Full Name */
            full_name?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Default Meal Type Id */
            default_meal_type_id?: string | null;
        };
        /** PasswordSet */
        PasswordSet: {
            /** Password */
            password: string;
        };
        /** PeriodReportOut */
        PeriodReportOut: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
            /** Halls */
            halls: components["schemas"]["HallPeriodReportOut"][];
            /** Grand Total */
            grand_total: number;
            /** Grand Reserve Total */
            grand_reserve_total: number;
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
        };
        /**
         * RuleKind
         * @enum {string}
         */
        RuleKind: "recurring" | "one_off";
        /** ScheduleRuleCreate */
        ScheduleRuleCreate: {
            kind: components["schemas"]["RuleKind"];
            /** Meal Kinds */
            meal_kinds: components["schemas"]["MealKind"][];
            /** Hall Ids */
            hall_ids: string[];
            /**
             * Weekdays
             * @default []
             */
            weekdays: number[];
            /**
             * Dates
             * @default []
             */
            dates: string[];
        };
        /** ScheduleRuleOut */
        ScheduleRuleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["RuleKind"];
            /** Is Active */
            is_active: boolean;
            /** Meal Kinds */
            meal_kinds: components["schemas"]["MealKind"][];
            /** Hall Ids */
            hall_ids: string[];
            /** Weekdays */
            weekdays: number[];
            /** Dates */
            dates: string[];
        };
        /** ScheduleRuleUpdate */
        ScheduleRuleUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Meal Kinds */
            meal_kinds?: components["schemas"]["MealKind"][] | null;
            /** Hall Ids */
            hall_ids?: string[] | null;
            /** Weekdays */
            weekdays?: number[] | null;
            /** Dates */
            dates?: string[] | null;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Generation Days */
            generation_days: number;
            /** Deadline Offset Days */
            deadline_offset_days: number;
            /**
             * Deadline Time
             * Format: time
             */
            deadline_time: string;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Generation Days */
            generation_days?: number | null;
            /** Deadline Offset Days */
            deadline_offset_days?: number | null;
            /** Deadline Time */
            deadline_time?: string | null;
        };
        /** TypeCountOut */
        TypeCountOut: {
            /** Meal Type Id */
            meal_type_id: string | null;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /** Default Meal Type Id */
            default_meal_type_id: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "eater" | "admin" | "accountant" | "operator";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_defaults_api_v1_me_defaults_get: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_defaults_api_v1_me_defaults_put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefaultsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_v1_me_calendar_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayStateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_day_api_v1_me_days__day_date__put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                day_date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meal_types_api_v1_catalog_meal_types_get: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTypeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                hall_id?: string | null;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requests_for_day_api_v1_admin_requests_get: {
        parameters: {
            query: {
                day_date: string;
                hall_id?: string | null;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_for_user_api_v1_admin_requests__user_id___day_date__put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
                day_date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_defaults_api_v1_admin_users__user_id__defaults_get: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_defaults_api_v1_admin_users__user_id__defaults_put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefaultsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_calendar_api_v1_admin_users__user_id__calendar_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayStateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_report_api_v1_accountant_report_get: {
        parameters: {
            query: {
                date: string;
                hall_id?: string | null;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    period_report_api_v1_accountant_report_period_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                hall_id?: string | null;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_report_export_api_v1_accountant_report_export_get: {
        parameters: {
            query: {
                date: string;
                hall_id?: string | null;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    period_report_export_api_v1_accountant_report_period_export_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                hall_id?: string | null;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_halls_api_v1_operator_halls_get: {
        parameters: {
            query?: {
                only_active?: boolean;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hall_api_v1_operator_halls_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hall_api_v1_operator_halls__hall_id__put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                hall_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HallOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hall_api_v1_operator_halls__hall_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                hall_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meal_types_api_v1_operator_meal_types_get: {
        parameters: {
            query?: {
                only_active?: boolean;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTypeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_type_api_v1_operator_meal_types_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealTypeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_type_api_v1_operator_meal_types__meal_type_id__put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                meal_type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_type_api_v1_operator_meal_types__meal_type_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                meal_type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_operator_users_get: {
        parameters: {
            query?: {
                role?: components["schemas"]["UserRole"] | null;
                hall_id?: string | null;
                only_active?: boolean;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorUserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_operator_users_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_operator_users__user_id__put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_operator_users__user_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v1_operator_users__user_id__password_put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_halls_api_v1_operator_users__user_id__halls_put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HallsSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_operator_settings_get: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_v1_operator_settings_put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_operator_schedule_rules_get: {
        parameters: {
            query?: {
                only_active?: boolean;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_v1_operator_schedule_rules_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_operator_schedule_rules__rule_id__put: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_operator_schedule_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_v1_operator_days_regenerate_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_api_v1_operator_logs_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                user_id?: string | null;
                limit?: number;
            };
            header: {
                "x-device-fingerprint": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
