"""meal type icon

Revision ID: 01fe93c155e1
Revises: a6a35f6d447a
Create Date: 2026-10-03 13:11:14.721786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fe93c155e1'
down_revision: Union[str, Sequence[str], None] = 'a6a35f6d447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_types', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_types', 'icon')
    # ### end Alembic commands ###
