"""phase3 schedule and calendar

Revision ID: 47fd9e150cb3
Revises: ec48246c33d7
Create Date: 2026-10-03 11:39:15.611861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '47fd9e150cb3'
down_revision: Union[str, Sequence[str], None] = 'ec48246c33d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_date'), 'days', ['date'], unique=True)
    op.create_table('schedule_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('recurring', 'one_off', name='rule_kind'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_hall_meals',
    sa.Column('day_id', sa.Uuid(), nullable=False),
    sa.Column('hall_id', sa.Uuid(), nullable=False),
    sa.Column('meal_kind', postgresql.ENUM('breakfast', 'lunch', 'snack', 'dinner', name='meal_kind', create_type=False), nullable=False),
    sa.Column('is_served', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day_id', 'hall_id', 'meal_kind')
    )
    op.create_table('schedule_rule_dates',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'specific_date')
    )
    op.create_table('schedule_rule_halls',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('hall_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'hall_id')
    )
    op.create_table('schedule_rule_meals',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('meal_kind', postgresql.ENUM('breakfast', 'lunch', 'snack', 'dinner', name='meal_kind', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'meal_kind')
    )
    op.create_table('schedule_rule_weekdays',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['schedule_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'weekday')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_rule_weekdays')
    op.drop_table('schedule_rule_meals')
    op.drop_table('schedule_rule_halls')
    op.drop_table('schedule_rule_dates')
    op.drop_table('day_hall_meals')
    op.drop_table('schedule_rules')
    op.drop_index(op.f('ix_days_date'), table_name='days')
    op.drop_table('days')
    sa.Enum(name='rule_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
